    - name: disable default redis module 
      command: dnf module disable redis -y
    
    - name: enable redis:7
      command: dnf module enable redis:7 -y

    - name: install redis 
      dnf: 
        name: redis
        state: present 

    - name: Update listen address from 127.0.0.1 to 0.0.0.0  in /etc/redis/redis.Configure
      replace:
        path: /etc/redis/redis.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: Update protected-mode from yes to no in /etc/redis/redis.Configure
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "protected-mode"
        line: "protected-mode no" 

    - name: enable and start redis 
      service: 
        name: redis 
        state: started
        enabled: yes