CATALOGUE_HOST: catalogue.backend-{{ env }}.daws84s.cloud
USER_HOST: user.backend-{{ env }}.daws84s.cloud
CART_HOST: cart.backend-{{ env }}.daws84s.cloud
SHIPPING_HOST: shipping.backend-{{ env }}.daws84s.cloud
PAYMENT_HOST: payment.backend-{{ env }}.daws84s.cloud