  - name: copy mongodb repo
    copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb server
    dnf: 
      name: mongodb-org
      state: installed

  - name: Start and enable mongo db 
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
    replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0
  - name: Restart mongodb service
    service:
      name: mongod
      state: restarted