- name: Configure {{ component }}
  hosts:  "{{ component }}"
  become: yes 
  # vars_files: 
  #   - vault/mysql.yml
  roles: #This will automatically load a folder called roles in current working directory 
    - "{{ component }}"
  