- name: App setup for payment 
  include_role: 
    name: common
    tasks_from: app-setup

- name: Python setup for payment 
  include_role: 
    name: common
    tasks_from: python-setup

- name: System setup for payment 
  include_role: 
    name: common
    tasks_from: systemd
