  - name: diable default niginx
    command: dnf module disable nginx -y
  
  - name: 
    command: dnf module enable nginx:1.24 -y
  
  - name: install nginx 
    dnf: 
      name: nginx
      state: present
  
  - name: Start & Enable Nginx service
    service:
      name: nginx 
      state: started 
      enabled: yes 

  - name: Remove html directory
    file: 
      path: /usr/share/nginx/html
      state: absent
  
  - name: Create a html directory 
    file:
      path: /usr/share/nginx/html
      state: directory
  
  - name: Download the frontend content
    get_url: 
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip
  
  - name: Unzip the frontend code
    unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes 
  
  - name: remove existing nginx .conf  
    file:
      path: /etc/nginx/nginx.conf
      state: absent
    
  - name: configuring nginx .conf file 
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: 
      - restart nginx 
  
