- name: Create app directory 
  file: 
    path: /app 
    state: directory

- name: Create roboshop system user 
  user: 
    name: roboshop
    shell: /sbin/nologin
    system: true 
    home: /app

- name: "Download the {{ component }} code"
  get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
    dest: "/tmp/{{ component }}.zip"
  
# This module thinks file exist on ansible control server, need to extract on to remote machine 
- name: Extract {{ component }} code 
  unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes  # File already exist in catalogue server 
